# Generated by Django 4.2 on 2023-04-19 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["name"],
                "verbose_name": "Project",
                "verbose_name_plural": "Project",
            },
        ),
    ]
