# Generated by Django 4.2 on 2023-04-09 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="userprofile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userprofile_skills",
                to="main.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="skills",
            field=models.ManyToManyField(
                blank=True, related_name="related_userprofiles", to="main.skill"
            ),
        ),
    ]
