# Generated by Django 4.2 on 2023-04-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_skill_userprofile_alter_userprofile_skills"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="skills",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="debugging_skills",
            field=models.ManyToManyField(
                blank=True, related_name="related_userprofiles", to="main.skill"
            ),
        ),
    ]
