# Generated by Django 4.2 on 2023-04-19 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_project_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accomplishment",
            options={
                "ordering": ["name"],
                "verbose_name": "Accomplishment",
                "verbose_name_plural": "Accomplishments",
            },
        ),
    ]
