# Generated by Django 4.2 on 2023-04-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_accomplishment_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="education",
            name="date",
        ),
        migrations.AddField(
            model_name="education",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="结束日期"),
        ),
        migrations.AddField(
            model_name="education",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="开始日期"),
        ),
    ]
