# Generated by Django 4.2 on 2023-04-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_remove_education_date_education_end_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="date",
        ),
        migrations.AddField(
            model_name="project",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="uni"
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="title",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="major"
            ),
        ),
    ]
