# Generated by Django 4.2 on 2023-04-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_remove_project_date_project_end_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="experience",
            options={
                "ordering": ["start_date"],
                "verbose_name": "Experience",
                "verbose_name_plural": "Experience",
            },
        ),
        migrations.RemoveField(
            model_name="education",
            name="description",
        ),
        migrations.RemoveField(
            model_name="experience",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="experience",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="experience",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="学校"
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="title",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="专业"
            ),
        ),
    ]
